---
language: rust
dist: trusty
sudo: required
services: docker
cache: cargo

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

script:
  - cargo build
  - cargo build --no-default-features
  - cargo test


matrix:
  include:

    # Test compatibility
    #
    # 1.39.0 is the oldest supported version of Rust. This value should NOT be
    # changed without prior discussion.
    #
    # This build also deploys docs
    - os: linux
      rust: 1.39.0
      before_script:
        - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
      script:
        # Ensure that the build works without default features
        - cargo build
        - cargo build --no-default-features
        - cargo test
        - cargo doc --no-deps
      after_success:
        - travis-cargo doc-upload
      install:

    # Test on latest stable
    - os: linux
      rust: stable
      script:
        # Ensure that the build works without default features
        - cargo build
        - cargo build --no-default-features
        - cargo test
      install:

notifications:
  email:
on_success: never
